CREATE TABLE receitas (
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    descricao VARCHAR(50) NOT NULL,
    valor DECIMAL(20,2) NOT NULL,
    data DATE NOT NULL,
    observacao VARCHAR(100) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
